# Docs: https://docs.travis-ci.com/user/languages/r/
# Validate your .travis.yml file at http://lint.travis-ci.org/

sudo: false

branches:
  except:
    - gh-pages

language: r

#cran: http://cran.cnr.berkeley.edu

# This repos setting doesn't seem to be working :/
#repos:
#  CRAN: http://cran.rstudio.com

cache: packages

# We don't need Latex so save time by telling Travis not to install it.
# Via https://docs.travis-ci.com/user/languages/r/#LaTeX-TexLive-Packages
latex: false
r_check_args: "--as-cran --timings"

# Test on 3 versions of R.
r:
  - release
  - devel
  - oldrel

# Build the manual.
r_build_args: ""

# Allow build to continue even if a suggested package cannot be installed.
r_check_force_suggests: false

# Test on both linux and OSX.
# See details at https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  - osx

env:
  global:
    # From https://github.com/tidyverse/dplyr/blob/master/.travis.yml
    # Docs: https://docs.travis-ci.com/user/speeding-up-the-build/#Makefile-parallelization-example
    - MAKEFLAGS="-j 2"
    # Via https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#create-your-travisyml-file
    - ENCRYPTION_LABEL: "99d96023b074"
    - COMMIT_AUTHOR_EMAIL: "chrisken@gmail.com"
    # Allow build to continue even if a suggested package cannot be installed.
    - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  # Report build completion status once non-"allow_failures" builds are done.
  fast_finish: true
  # Allow failures on OSX.
  allow_failures:
    - os: osx

# Install nlopt package to help nloptr install.
addons:
  apt:
    packages:
      - libnlopt-dev

##########################
# Code coverage

r_github_packages:
  - jimhester/covr
  - hadley/pkgdown

after_success:
  # Only check test coverage for R = release and OS = linux.
  - test ${TRAVIS_R_VERSION_STRING} == "release" && test ${TRAVIS_OS_NAME} == "linux" && Rscript -e 'covr::codecov()'
  # Update pkgdown documentation if we're on the linux build and R version = release.
  - test ${TRAVIS_OS_NAME} == "linux" && test ${TRAVIS_R_VERSION_STRING} == "release" && ./scripts/deploy_pkgdown.sh

after_failure:
  - ./travis-tool.sh dump_logs
